- name: Add PostgreSQL repo
  yum: name="{{ postgresql_repo }}" state=present

- name: yum install {{ postgresql_server_pkg_name }}
  yum: name="{{ postgresql_server_pkg_name }}" state=installed

- name: initdb
  command: /usr/pgsql-{{ version }}/bin/postgresql{{ version |replace('.', '') }}-setup initdb creates="{{ postgresql_data_dir }}/base"
