- name: Add PostgreSQL repo
  yum: name="{{ postgresql_repo }}" state=present

- name: yum install {{ postgresql_server_pkg_name }}
  yum: name="{{ postgresql_server_pkg_name }}" state=installed

- name: initdb
  command: service postgresql-{{ version }} initdb creates="{{ postgresql_data_dir }}/base"

